### ISSUE TITLE
new users are registered for more than one time

### ISSUE THREAD

**Issue by Amraish** [guillaumev/teca#82]
Dear, 

some new users, if you check the people table, you see they are registered more than one time, could you please fix the issue, why this happens? 

Thanks 
Nedaa

**Comment by guillaumev** [comment]
Hi Nedaa,
Do you have some examples ?

**Comment by Amraish** [comment]
here ...
Chantal Jamotte
chantal.jamotte@skynet.be	Yes		19 hours 30 min	3 hours 42 min ago	edit Cancel account

Chantal Jamotte
chantal.jamotte@skynet.be	Yes		19 hours 30 min	4 hours 1 min ago	edit Cancel account


there are evermore if you go back with the pages ... 

Thanks

**Comment by Amraish** [comment]
This person as well, she is intern for TECA, she registered only once:

Hanna Weber
hanna.weber@posteo.de	Yes	
unauthenticated
22 hours 2 min		

Hanna Weber
hanna.weber@posteo.de	Yes	
editor
22 hours 3 min	35 min 31 sec ago

**Comment by guillaumev** [comment]
Ok after looking into this: the users that you see as duplicates all have one account set as "unauthenticated". This means that they tried to register once, for some reason it didn't work (because they didn't receive the confirmation email) and then they registered again, and this time it worked. 
They therefore validated one account, but not the other one. The account that hasn't been validated will be automatically deleted after 2 weeks, so I think everything is ok here.

Closing this, feel free to reopen if needed.
